[package]
name = "tao-syntax"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maybe_box = "1.0"
chumsky = { git = "https://github.com/zesterer/chumsky.git" } #"0.3.2"
internment = "0.5"
