[package]
name = "tao_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
tao_syntax = { path = "../syntax" }
ariadne = "0.1"
hashbrown = "0.11"
lazy_static = "1.4"

[dev-dependencies]
ariadne = "0.1"
rustyline = "9.0"
